default: &default
  adapter: postgresql
  pool: 10
  username: admin
  password: 123456
  host: localhost

development:
  <<: *default
  database: doorkeeper_provider

test:
  <<: *default
  database: doorkeeper_provider

production:
  <<: *default
  database: doorkeeper_provider
